name: go-mod-tidier
description: 'Run go mod tidy on one or more go.mod files'
inputs:
  files:  # id of input
    description: 'List of go.mod files to run go mod tidy on'
    required: true
    default: go.mod
outputs:
  changedfiles: # id of output
    description: 'List of files that were changed'
runs:
  using: 'node12'
  main: 'index.js'
