name: Mod the Hoople
on:
  pull_request:
    types: [ opened, reopened, labeled, unlabeled, edited, synchronize ]

jobs:
  mod_cleaner:
    runs-on: ubuntu-latest
    name: Clean up dependabot mods to go.sum files
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14.0'
    - name: mod-tidier
      uses:  ./.github/actions/modtidy/
      id: modtidy
      with:
        files: '**/go.mod'
        gosum_only: false
    - name: go-sum
      run: |
          go mod tidy -v
    - name: my-test
      run: |
        echo ${GITHUB_ACTOR}
    - name: auto-commit
      uses: stefanzweifel/git-auto-commit@v4
      with:
        commit_message: Auto-fix go.sum changes
    - name: Show changes
      run: echo "Changes detected: ${{ steps.auto-commit.outputs.changes_detected }}"
