name: Mod the Hoople
on:
  pull_request:
    types: [ opened, reopened, labeled, unlabeled, edited, synchronize ]

jobs:
  mod_cleaner:
    runs-on: ubuntu-latest
    name: A job to clean up go.sum
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14.0'
    - name: mod-tidier
      uses:  ./.github/actions/tidysum/
      id: tidysum
      with:
        files: '**/go.mod'
        gosum_only: true
    - name: go-sum
      run: |
          go mod tidy -v
    - name: Dump Github context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo ${GITHUB_CONTEXT}
    - name: my-test
      run: |
        echo ${GITHUB_ACTOR}
    # Use the output from the `go-sum` step
    - name: Get the output time
      run: echo "The time was ${{ steps.go-sum.outputs.time }}"
