name: Mod the Hoople
on:
  pull_request:
    types: [ opened, reopened, labeled ]

jobs:
  mod_cleaner:
    runs-on: ubuntu-latest
    name: A job to clean up go.mod/go.sum
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14.0'
    - name: go-sum
      run: |
          go mod tidy
          git diff
    # Use the output from the `go-sum` step
    - name: Get the output time
      run: echo "The time was ${{ steps.go-sum.outputs.time }}"
